Homework 3 - Data Wrangling/Visualization/Analysis

Option 2: I chose this option to capture data about multiple ETFs across the market to compare data and
performance. I am going to capture data from specifically the S&P 500, Nasdaq, VIX and the Dow. I am sourcing my data from the website called Federal Reserve Economic Data.

In [2]:
#Basic imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests 
import bs4
import json
from pathlib import Path

In [4]:
#Setup folders
raw_data_path = "data/raw"
output_path = "output"

In [13]:
#Build a dictionary to feed a function to pull S&P 500, Nasdaq, VIX and the Dow - using the id code
source_data_dict = {"SP500":"S&P 500", "NASDAQCOM":"NASDAQ", "VIXCLS":"VIX", "DJIA":"Dow Jones"}

source_data_dict

{'SP500': 'S&P 500',
 'NASDAQCOM': 'NASDAQ',
 'VIXCLS': 'VIX',
 'DJIA': 'Dow Jones Industrial Average'}

In [6]:
#Configure function to pull based on the dictionary for the ETFs
def pull_source_data(series_id, series_name):
    """ Reading the data series from FRED """
    ##configure url
    url = f"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series_id}"

    ##read the data
    source_df = pd.read_csv(url)

    ##rename the columns for visualization
    source_df = source_df.rename(columns={"observation_date":"date"})
    source_df = source_df.rename(columns={series_id:"value"})

    ##adding the columns 
    source_df["series_id"] = series_id
    source_df["series_name"] = series_name

    return source_df

In [10]:
##Test to view S&P 500 data
SP500_df = pull_source_data("SP500", "S&P 500")

SP500_df.head(10)

         date    value series_id series_name
0  2016-08-19  2183.87     SP500     S&P 500
1  2016-08-22  2182.64     SP500     S&P 500
2  2016-08-23  2186.90     SP500     S&P 500
3  2016-08-24  2175.44     SP500     S&P 500
4  2016-08-25  2172.47     SP500     S&P 500
5  2016-08-26  2169.04     SP500     S&P 500
6  2016-08-29  2180.38     SP500     S&P 500
7  2016-08-30  2176.12     SP500     S&P 500
8  2016-08-31  2170.95     SP500     S&P 500
9  2016-09-01  2170.86     SP500     S&P 500

In [11]:
##Test to view NASDAQ data
NASDAQ_df = pull_source_data("NASDAQCOM", "NASDAQ")

NASDAQ_df.head(10)

         date   value  series_id series_name
0  1971-02-05  100.00  NASDAQCOM      NASDAQ
1  1971-02-08  100.84  NASDAQCOM      NASDAQ
2  1971-02-09  100.76  NASDAQCOM      NASDAQ
3  1971-02-10  100.69  NASDAQCOM      NASDAQ
4  1971-02-11  101.45  NASDAQCOM      NASDAQ
5  1971-02-12  102.05  NASDAQCOM      NASDAQ
6  1971-02-15     NaN  NASDAQCOM      NASDAQ
7  1971-02-16  102.19  NASDAQCOM      NASDAQ
8  1971-02-17  101.74  NASDAQCOM      NASDAQ
9  1971-02-18  101.42  NASDAQCOM      NASDAQ

In [12]:
##Test to view VIX data
VIX_df = pull_source_data("VIXCLS", "VIX")

VIX_df.head(10)

         date  value series_id series_name
0  1990-01-02  17.24    VIXCLS         VIX
1  1990-01-03  18.19    VIXCLS         VIX
2  1990-01-04  19.22    VIXCLS         VIX
3  1990-01-05  20.11    VIXCLS         VIX
4  1990-01-08  20.26    VIXCLS         VIX
5  1990-01-09  22.20    VIXCLS         VIX
6  1990-01-10  22.44    VIXCLS         VIX
7  1990-01-11  20.05    VIXCLS         VIX
8  1990-01-12  24.64    VIXCLS         VIX
9  1990-01-15  26.34    VIXCLS         VIX

In [14]:
##Test to view DJIA data
DJIA_df = pull_source_data("DJIA", "Dow Jones")

DJIA_df.head(10)

         date     value series_id series_name
0  2016-08-19  18552.57      DJIA   Dow Jones
1  2016-08-22  18529.42      DJIA   Dow Jones
2  2016-08-23  18547.30      DJIA   Dow Jones
3  2016-08-24  18481.48      DJIA   Dow Jones
4  2016-08-25  18448.41      DJIA   Dow Jones
5  2016-08-26  18395.40      DJIA   Dow Jones
6  2016-08-29  18502.99      DJIA   Dow Jones
7  2016-08-30  18454.30      DJIA   Dow Jones
8  2016-08-31  18400.88      DJIA   Dow Jones
9  2016-09-01  18419.30      DJIA   Dow Jones